<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5MTpG63\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5MTpG63/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5MTpG63.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5MTpG63\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5MTpG63\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5MTpG63',
    'container.build_id' => '2612b9bb',
    'container.build_time' => 1586816044,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5MTpG63');
